# This is small check to confirm that the shell's limits for opening file
# descriptors is sufficiently high. This is relevant for our property tests, in
# which some tests rapidly create and destroy HTTP servers.
ulimit:
  script:
    - ulimit -Hn
    - ulimit -Sn

chainweb-nix-macos:
  script:
    - nix-build
    - nix-build -A ghc.chainweb.doc
    - scripts/collectArtifacts.sh
  artifacts:
    paths:
    - public/
    expire_in: 1 week

chainweb-nix-linux:
  script:
    - nix-build --argstr system x86_64-linux
  allow_failure: true

chainweb-stack:
  script:
    - nix-shell -p stack libiconv zlib ncurses --run "stack test --fast"

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
