stages:
  - prelude
  - build

cabal-setup:
  stage: prelude
  script:
    - nix-shell -p haskell.compiler.ghc844 cabal-install zlib --run "cabal new-update"

chainweb-nix-ghc84:
  stage: build
  script:
    - nix-build

chainweb-stack:
  stage: build
  script:
    - nix-shell -p stack libiconv zlib --run "stack test --fast"

chainweb-cabal-ghc84:
  stage: build
  script:
    - nix-shell -p haskell.compiler.ghc844 cabal-install zlib --run "cabal new-build && cabal new-test"
