ulimit:
  script:
    - ulimit -Hn
    - ulimit -Sn
    - nix-shell --run "ulimit -Hn"
    - nix-shell --run "ulimit -Sn"

chainweb-nix-macos:
  script:
    - nix-build
    - nix-build -A ghc.chainweb.doc
    - scripts/collectArtifacts.sh
  artifacts:
    paths:
    - public/
    expire_in: 1 week

chainweb-nix-linux:
  script:
    - nix-build --argstr system x86_64-linux

chainweb-stack:
  script:
    - nix-shell -p stack libiconv zlib ncurses --run "stack test --fast"

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
