# This is small check to confirm that the shell's limits for opening file
# descriptors is sufficiently high. This is relevant for our property tests, in
# which some tests rapidly create and destroy HTTP servers.
ulimit:
  script:
    - ulimit -Hn
    - ulimit -Sn

nix-macos:
  tags:
    - macos
  script:
    - nix-build
    - nix-build -A ghc.chainweb.doc
    - scripts/collectArtifacts.sh
  artifacts:
    paths:
    - public/
    expire_in: 1 week

nix-shell-macos:
  tags:
    - macos
  script:
    - nix-shell --run "echo Done with shell test"

nix-linux:
  tags:
    - linux
  script:
    - nix-build
    - nix-build -A ghc.chainweb.doc
    - scripts/collectArtifacts.sh
  artifacts:
    paths:
    - public/
    expire_in: 1 week

nix-shell-linux:
  tags:
    - linux
  script:
    - nix-shell --run "echo Done with shell test"

# DB 2019-01-17: Disabling so we have some CI for now. Stuart and I worked on
# fixing this and have a plan of attack.
# chainweb-stack:
#   script:
#     - nix-shell -p libiconv zlib ncurses gmp git perl --run "stack test --fast"

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
