stages:
  - prelude
  - build

cabal-setup:
  stage: prelude
  script:
    - nix-shell -p haskell.compiler.ghc822 cabal-install zlib --run "cabal new-update"

chainweb-nix-ghc82:
  stage: build
  script:
    - nix-build

chainweb-stack:
  stage: build
  script:
    - nix-shell -p stack libiconv zlib --run "stack test --fast"

chainweb-cabal-ghc82:
  stage: build
  script:
    - nix-shell -p haskell.compiler.ghc822 cabal-install zlib --run "cabal new-build && cabal new-test"

chainweb-cabal-ghc82-dev:
  stage: build
  script:
    - nix-shell -p haskell.compiler.ghc822 cabal-install zlib --run "cabal new-build -fdev && cabal new-test -fdev"

chainweb-cabal-ghc84:
  stage: build
  script:
    - nix-shell -p haskell.compiler.ghc843 cabal-install zlib --run "cabal new-build && cabal new-test"

chainweb-cabal-ghc84-dev:
  stage: build
  script:
    - nix-shell -p haskell.compiler.ghc843 cabal-install zlib --run "cabal new-build -fdev && cabal new-test -fdev"
